### ISSUE TITLE
Issue changing API url to fetch WEM data instead of NEM data 

### ISSUE THREAD

**Issue by aleith** [opennem/opennem-widget#28]
I built a local yarn instance of the widget and when I changed the API url in `index.js` line 7 from

> `const dataURL = "https://data.opennem.org.au/v3/stats/au/NEM/power/7d.json"`

to

> `const dataURL = "https://data.opennem.org.au/v3/stats/au/WEM/power/7d.json"  `

there is no data fetched. the graph background draws but no data rendered. 

this change was suggested by someone and I think they got the URL from the main openNEM project.

Here's their fork [here](https://github.com/chiragkanjariya/opennem-widget).

If there is a reasonably simple fix for this I expect SEN might be willing to pay for it, @simonhac, @chienleng, @nc9

**Comment by nc9** [comment]
Thanks for reporting this - let us take a look at it and we'll update here.

**Comment by aleith** [comment]
Cheers @nc9 !

pls see this related widget [rendering issue/enhancement request](https://github.com/opennem/opennem-widget/issues/29) also.

**Comment by aleith** [comment]
Hey @nc9 is there an ETA on this enhancement/fix? Cost estimate?

I get the feeling SEN is about to spend money on someone replicating this as PHP code for our new website using the NEMwatch API and I'd much rather spend that on enhancing this code base which we can extend to other features, including our representing our modelled data output in realtime according to recent weather conditions.

**Comment by aleith** [comment]
Hi @nc9 Nik just wondering if there's any progress to report on this. Do we know why api call for WEM data is failing?

**Comment by chienleng** [comment]
@aleith apologies for getting a while to get back to things. I am back on a regular schedule now.

the 'original' widget was first created to allow external users to 'embed' opennem NEM view in their sites. One big issue of that version is the javascript bundle size as it incorporates a major chunk of the front end code used by OpenNEM site. 

When I wrote this version of the widget, the single focus was to dramatically cut down the javascript size. In doing that, it is not as flexible as the original version in detecting variations of the dataset and also it was written before we had WEM data. 

I will take a stab on this later this week and will let you know how it goes.

**Comment by chienleng** [comment]
PR to support WEM data: https://github.com/opennem/opennem-widget/pull/31

<img width="1048" alt="Screen Shot 2022-09-29 at 3 17 45 pm" src="https://user-images.githubusercontent.com/349944/192945108-30db1b06-3041-474c-9bdc-d013e5e814a5.png">

To run and build this for your usage:
* clone the latest version (v4.0.1): https://github.com/opennem/opennem-widget/releases/tag/4.0.1
* update `src/index.js` - change `region` to `WEM` and `showLast3Days` to `false`. This will fetch WEM path and show all days instead of last 3 days.
* you can preview and test it out using `yarn start`.
* to output a version you can host, run `yarn build` and then copy the files inside `/dist` is to your server.

**Comment by aleith** [comment]
Hi @chienleng — that makes sense, and thanks so much for doing this revision. WA says hi, even though Im in VIC. 

I need to repair the Mac I have this all installed on with battery and SSD but once I do that I'll build and deploy. 

Thanks so much this is a life saver for SEN and we want to put it on our home page. 

I have a friend who is a retired programmer who is interested in forking OpenNEM to display modelled energy mixes and accomodate the different interface elements we'd need. He's had a look at the full version of OpenNEM frontend code base and thinks it's worth tackling, but he's tied up until Christmas on another project, maybe until April. But then we can get back into it.
