### ISSUE TITLE
3 days of data shown even in wide browser page, I think it is supposed to be 7 day view. 

### ISSUE THREAD

**Issue by aleith** [opennem/opennem-widget#29]
this line from `index.js` would suggest a 7 day view is intended but I always see 3 day view in various browser windows when I build this and run it with `yarn` locally. Also 3-day on reneweconomy.com so I'm thinking now this is intentional

`const dataURL = "https://data.opennem.org.au/v3/stats/au/NEM/power/7d.json"`

Be great if adjustments to url rendered different time periods.

**Comment by aleith** [comment]
<img width="1982" alt="Screen Shot 2022-06-29 at 2 42 25 pm" src="https://user-images.githubusercontent.com/1528794/176353320-fa5b75c4-f2bc-4c1d-a30e-e0e201425c35.png">

**Comment by chienleng** [comment]
latest update now supports full 7 day view, just update `showLast3Days` to `false`:
 https://github.com/opennem/opennem-widget/blob/712fcc43f7c01e2b37f7c86b3e224c6f43d5227a/src/index.js#L17

**Comment by aleith** [comment]
ah, thanks for that @chienleng !
